- name: rm -rf /var/cache/yum
  file:
    path: /var/cache/yum
    state: absent
- name: add Node.js v9 Yum Repository
  shell: curl --silent --location https://rpm.nodesource.com/setup_9.x | sudo bash -
- name: yum clean all
  shell: yum clean all
- name: install Node.js
  yum:
    name: nodejs
    state: latest